dataset:
  root: $EXPYRUN_CWD/data/trasein_patch
  val_root: $EXPYRUN_CWD/data/trasein_val_patch
  video_ids: []  # Take all
  delta_t: 4
  patch_size: 32
  elastic:
    prob: 0.5
    alpha: 20.0
    sigma: 5.0
  affine:
    prob: 0.5
    max_rotate: 5.0
    max_translate: 2.0
  erase:
    prob: 1.0  # As cropping is used afterward, only 25% of images are truly impacted
    scale: [0.005, 0.05]
  motion_blur:
    prob: 0.1  # Rarely adds motion blur
    max_displacement: 9
  blur_shot_noise:
    prob: 0.5
    sigma: [0.1, 1.0]
    psnr: [20.0]
  jitter:
    prob: 0.5
    brightness: 0.05
    contrast: 0.05
